name: "Danger JS"
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: install deps
        run: |
          yarn
      - name: Danger
        run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}